### ISSUE TITLE
Text in first child tab should always inherit from parent tab

### ISSUE THREAD

**Issue by logan-reynolds** [davidherney/moodle-format_onetopic#92]
In order to set a top-level tab as, for example, "English", it appears that all of the child topics need to be set with "English" as the text of the first tab in the sublevel in order for it to show when child topics are hidden. Otherwise the text in the first child tab is pulled from the settings in the first visible child section.  This issue is to correct the tab text inheritance so that it is always defaulted to the parent tab instead of the first visible same-level tab.

**Comment by davidherney** [comment]
Fixed in commit https://github.com/davidherney/moodle-format_onetopic/commit/9df2e8592a1a94a30da49f0b2bf6eb2b29f5cb6c

Thx

**Comment by logan-reynolds** [comment]
During testing the newest M39 version we discovered that this was not fixed, and the issue with text in first child tab is still not inheriting from the parent tab.  Could you reopen this issue, or should a new issue be created?
